# Generated by Django 6.0.5 on 2026-05-23 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categorie', verbose_name='cathegorie'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(blank=True, max_length=62, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=62, null=True, verbose_name='prix'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(choices=[('ordinateur', 'ordinateur'), ('accessoire', 'accessoire'), ('fournisseur', 'fournisseur'), ('logiciel', 'logiciel')], max_length=62),
        ),
    ]
